#!/usr/bin/env bash
# install.sh — Inte-School one-command installer for school.inte.team
# Usage:  sudo bash install.sh [--repo <git-url>] [--branch <branch>]
# Tested: Ubuntu 22.04 / 24.04

set -euo pipefail

# ─── Config ────────────────────────────────────────────────────────────────────
DOMAIN="school.inte.team"
REPO_URL="${REPO_URL:-git@github.com:inteteam/inte-school.git}"
BRANCH="${BRANCH:-main}"
INSTALL_DIR="/opt/inte-school"
DOCKER_NETWORK="proxy-tier"

# ─── Helpers ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

info()    { echo -e "${GREEN}[inte-school]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

require() {
    command -v "$1" &>/dev/null || die "'$1' is required but not installed."
}

gen_secret() {
    openssl rand -base64 40 | tr -d '/+=' | head -c 40
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --repo)   REPO_URL="$2";  shift 2 ;;
            --branch) BRANCH="$2";    shift 2 ;;
            *) die "Unknown argument: $1" ;;
        esac
    done
}

# ─── Pre-flight ─────────────────────────────────────────────────────────────────
preflight() {
    [[ $EUID -eq 0 ]] || die "Run as root: sudo bash install.sh"
    require git
    require docker
    require openssl

    docker compose version &>/dev/null \
        || die "Docker Compose v2 plugin not found. Install it and retry."

    info "Pre-flight checks passed."
}

# ─── System dependencies ────────────────────────────────────────────────────────
install_deps() {
    info "Updating apt and installing prerequisites…"
    apt-get update -qq
    apt-get install -y -qq git curl openssl ca-certificates
}

# ─── Shared Docker network ──────────────────────────────────────────────────────
ensure_proxy_network() {
    if ! docker network inspect "$DOCKER_NETWORK" &>/dev/null; then
        info "Creating Docker network: $DOCKER_NETWORK"
        docker network create "$DOCKER_NETWORK"
    else
        info "Docker network '$DOCKER_NETWORK' already exists — skipping."
    fi
}

# ─── Clone or update repo ───────────────────────────────────────────────────────
clone_repo() {
    if [[ -d "$INSTALL_DIR/.git" ]]; then
        warn "Directory $INSTALL_DIR already exists — pulling latest changes."
        git -C "$INSTALL_DIR" fetch origin
        git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
    else
        info "Cloning $REPO_URL (branch: $BRANCH) → $INSTALL_DIR"
        git clone --depth=1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
    fi
}

# ─── Generate .env ──────────────────────────────────────────────────────────────
create_env() {
    local env_file="$INSTALL_DIR/.env"

    if [[ -f "$env_file" ]]; then
        warn ".env already exists — skipping generation. Delete it to regenerate."
        return
    fi

    info "Generating .env from .env.production.example template…"
    cp "$INSTALL_DIR/.env.production.example" "$env_file"

    local app_key db_pass redis_pass reverb_id reverb_key reverb_secret

    app_key="base64:$(openssl rand -base64 32)"
    db_pass="$(gen_secret)"
    redis_pass="$(gen_secret)"
    reverb_id="$(openssl rand -hex 6)"
    reverb_key="$(gen_secret)"
    reverb_secret="$(gen_secret)"

    sed -i "s|^APP_KEY=.*|APP_KEY=${app_key}|"                              "$env_file"
    sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=${db_pass}|"                      "$env_file"
    sed -i "s|^REDIS_PASSWORD=.*|REDIS_PASSWORD=${redis_pass}|"             "$env_file"
    sed -i "s|^REVERB_APP_ID=.*|REVERB_APP_ID=${reverb_id}|"                "$env_file"
    sed -i "s|^REVERB_APP_KEY=.*|REVERB_APP_KEY=${reverb_key}|"             "$env_file"
    sed -i "s|^REVERB_APP_SECRET=.*|REVERB_APP_SECRET=${reverb_secret}|"    "$env_file"

    chmod 640 "$env_file"
    info ".env written."

    # Write docker-compose.override.yml so Redis uses the generated password.
    # This file is gitignored — it never touches the tracked docker-compose.yml.
    cat > "$INSTALL_DIR/docker-compose.override.yml" <<EOF
# Generated by install.sh — gitignored, do not commit.
services:
  redis:
    command: redis-server --appendonly yes --requirepass ${redis_pass}
EOF
    info "docker-compose.override.yml written (Redis password applied)."
}

# ─── Build & start containers ────────────────────────────────────────────────────
start_containers() {
    info "Building and starting production containers…"
    cd "$INSTALL_DIR"
    docker compose --profile prod pull --quiet
    docker compose --profile prod up -d --build
}

# ─── Install PHP dependencies ───────────────────────────────────────────────────
# Must run before any `php artisan` command — the Dockerfile only installs
# the Composer binary; vendor/ is never baked into the image.
install_composer_deps() {
    info "Installing PHP dependencies (composer install --no-dev)…"
    docker compose exec -T php-fpm composer install \
        --no-dev \
        --optimize-autoloader \
        --no-interaction \
        --prefer-dist
}

# ─── Wait for php-fpm ───────────────────────────────────────────────────────────
wait_for_phpfpm() {
    info "Waiting for php-fpm to be ready…"
    local attempts=0
    until docker compose exec -T php-fpm php -r "echo 'ok';" &>/dev/null; do
        sleep 2
        (( attempts++ ))
        [[ $attempts -lt 20 ]] || die "php-fpm did not become ready in time."
    done
}

# ─── Database setup ─────────────────────────────────────────────────────────────
setup_database() {
    info "Waiting for PostgreSQL to be ready…"
    local attempts=0
    until docker compose exec -T postgresql pg_isready -U inteschool &>/dev/null; do
        sleep 2
        (( attempts++ ))
        [[ $attempts -lt 30 ]] || die "PostgreSQL did not become ready in time."
    done

    info "Running migrations…"
    docker compose exec -T php-fpm php artisan migrate --force

    info "Seeding essential data…"
    docker compose exec -T php-fpm php artisan db:seed --force
}

# ─── Generate VAPID keys ────────────────────────────────────────────────────────
generate_vapid() {
    info "Generating VAPID keys for Web Push…"
    local vapid_output
    vapid_output=$(docker compose exec -T php-fpm php artisan vapid:generate 2>&1 || true)

    if echo "$vapid_output" | grep -q "VAPID_PUBLIC_KEY"; then
        local pub priv
        pub=$(echo  "$vapid_output" | grep VAPID_PUBLIC_KEY  | head -1 | cut -d= -f2 | tr -d '"' | tr -d ' ')
        priv=$(echo "$vapid_output" | grep VAPID_PRIVATE_KEY | head -1 | cut -d= -f2 | tr -d '"' | tr -d ' ')

        if [[ -n "$pub" && -n "$priv" ]]; then
            sed -i "s|^VAPID_PUBLIC_KEY=.*|VAPID_PUBLIC_KEY=${pub}|"    "$INSTALL_DIR/.env"
            sed -i "s|^VAPID_PRIVATE_KEY=.*|VAPID_PRIVATE_KEY=${priv}|" "$INSTALL_DIR/.env"
            info "VAPID keys written to .env"
        else
            warn "Could not parse VAPID output — set VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY in .env manually."
        fi
    else
        warn "vapid:generate unavailable or failed. Set VAPID keys in .env manually."
    fi
}

# ─── Build frontend assets ───────────────────────────────────────────────────────
# npm service is profile:dev so we pass --profile dev for the one-off build run.
# npm install must run before npm run build — node_modules are owned by Docker.
build_assets() {
    info "Installing npm dependencies…"
    cd "$INSTALL_DIR"
    docker compose --profile dev run --rm npm sh -c "npm install"

    info "Building frontend assets…"
    docker compose --profile dev run --rm npm sh -c "npm run build"
}

# ─── Artisan optimizations ───────────────────────────────────────────────────────
optimize() {
    info "Optimizing Laravel for production…"
    docker compose exec -T php-fpm php artisan config:cache
    docker compose exec -T php-fpm php artisan route:cache
    docker compose exec -T php-fpm php artisan view:cache
    docker compose exec -T php-fpm php artisan event:cache
}

# ─── Restart workers after asset build ──────────────────────────────────────────
restart_workers() {
    info "Restarting queue worker and Reverb…"
    docker compose up -d --build queue-worker
    docker compose restart reverb
}

# ─── Post-install summary ────────────────────────────────────────────────────────
summary() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║        Inte-School installed successfully!        ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "  URL:          https://${DOMAIN}"
    echo "  Install dir:  ${INSTALL_DIR}"
    echo "  Env file:     ${INSTALL_DIR}/.env  (keep secret)"
    echo ""
    echo "  Next steps:"
    echo "  1. Set RESEND_API_KEY, MAILGUN_DOMAIN, MAILGUN_SECRET in .env"
    echo "  2. Set GCS_* variables if using Google Cloud Storage"
    echo "  3. Set SMS_* variables if SMS fallback is needed"
    echo "  4. Ensure DNS A record for ${DOMAIN} points to this server"
    echo "  5. Caddy will provision an HTTPS certificate automatically"
    echo ""
    echo "  Useful commands (from ${INSTALL_DIR}):"
    echo "    docker compose exec php-fpm php artisan tinker"
    echo "    docker compose logs -f php-fpm"
    echo "    docker compose --profile prod ps"
    echo ""
}

# ─── Main ────────────────────────────────────────────────────────────────────────
main() {
    parse_args "$@"
    preflight
    install_deps
    ensure_proxy_network
    clone_repo
    create_env              # generates secrets → .env + docker-compose.override.yml
    start_containers        # docker compose --profile prod up -d --build
    wait_for_phpfpm         # php-fpm must respond before composer/artisan calls
    install_composer_deps   # vendor/ — MUST come before any php artisan command
    setup_database          # wait for postgres → migrate → seed
    generate_vapid          # php artisan vapid:generate
    build_assets            # npm install → npm run build (--profile dev)
    optimize                # config/route/view/event cache
    restart_workers         # queue-worker + reverb pick up built assets
    summary
}

main "$@"
